name: kynd
description: "A new Flutter project."


publish_to: 'none' 




version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'







dependencies:
  flutter:
    sdk: flutter


  
  # --------------- PACKAGES --------------

  # Utility
  http: ^1.2.1
  # date formating and all
  intl: ^0.19.0
  # prints beautiful logs
  logger: ^2.3.0
  # redirect users to external web page
  url_launcher: ^6.3.0
  # animated page movements
  smooth_page_indicator: ^1.1.0
  # svg images
  flutter_svg: ^2.0.10+1
  # saving ofline
  shared_preferences: ^2.2.3
#  #To Product user ofline
#  provider: ^6.1.2
  # carousel slider to display images
  carousel_slider: ^4.2.1
   # for getting number on icon
  badges: ^3.1.2
   # for getting the dotted line to paste photo in add products
  dotted_border: ^2.1.0
  # for selecting file in admin
  file_picker: ^8.0.5
  # for cloudinary used for images and media for app; (beter than mongodb for files)
  cloudinary_public: ^0.23.1
  # for lottie animations loading screen_brightness:
  lottie: ^3.1.2
  # for showing read more option
  readmore: ^3.0.0


  ## Payments---------------
  # for razorpay
  razorpay_flutter: ^1.3.7

  #for maps-----------------
  google_maps_flutter: ^2.7.0
  # for location
#  location: ^6.0.2
  geocoding: ^3.0.0
#  instead of above both packages the geolocator does the both with higher accuracy
  geolocator: ^12.0.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8


  # State data_management:
  get: ^4.6.6

  sliver_tools: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  

  
  flutter_lints: ^3.0.0





flutter:

  
  
  
  uses-material-design: true

  # ------------------- ASSETS ------------------
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/images/profile.jpg
    - assets/svgs/
    - assets/lottie/


  # ------------------- FONTS --------------------
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500  # Adjusted weight to 500 if you are using the standard Medium weight font file
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200

  
